version: 0.0
os: linux
files:
  - source: /appspec.yml
    destination: /home/ec2-user/gsmc-application/
  
  - source: /scripts
    destination: /home/ec2-user/gsmc-application/scripts/ 

permissions:
  - object: /home/ec2-user/gsmc-application/scripts/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
  BeforeInstall:
   
    - location: scripts/health-check.sh 
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: scripts/health-check.sh
      timeout: 180
      runas: ec2-user