version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
      
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
      
  ValidateService:
    - location: scripts/health-check.sh
      timeout: 60
      runas: ec2-user
      