version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/gsmc-application

permissions:
  - object: /home/ec2-user/gsmc-application/scripts/prod/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file

hooks:
  ApplicationStart:
    - location: scripts/prod/start.sh
      runas: ec2-user
