version: 0.0
os: linux
files:
  - source: /appspec.yml
    destination: /home/ec2-user/gsmc-application/

  - source: /scripts
    destination: /home/ec2-user/gsmc-application/scripts/prod/

permissions:
  - object: /home/ec2-user/gsmc-application/scripts/prod/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file

