version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/gsmc-application

permissions:
  - object: /home/ec2-user/gsmc-application/scripts/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/start_application.sh
      runas: ec2-user
