services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=gsmc'
      - 'MYSQL_PASSWORD=123456'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_USER=user'
    ports:
      - '3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'